######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk11

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "felixklauke"
    token:
      secure: FtkqgXXTqNhVgAIy8dFgGA3/1x4v5TCL3ND2TNUbM0/+G44nnI+6lGk7Vv2vUSs/eHam9/yK66OQqttFM4+AtAwILFgKwHr3QEJhbMhrzN3b8i7s/jMNDut+wTwUD6eMJ30OGAnrRcH5u3JaRfG2qv++rgUEE6r3DJI5PQs1vS/sz9r0XBZmxkh/Ts3LdYLqnMclHggU/IF8lCnWJLf1UkOTScbjVb9+FimurCC0fwkuaffXUnkZPi5jxhLgMCgV5fqmu0AlBAhBILaVCoMLOgqcPaefJbPQE+umOaoE/ptZItj0qgkbXvwH9FIp4hrvV6X5FNfwZvMYUZ/P2LFxU3NEpMzJsxsZZV64+vfqsVnIh64MKJ2WEc/GrDFvvRRbr3dcQRNOsPH3IQw560XsUNJSwxSDPRqf3UV087co/i/W5RtpM621uHK8Fm6s0z7uj44XRk7+fg0C27WQ103sbNnTgtwFtc1aCPo30teWcy7TDOEo3UCPho+hnVr0Ukp/c32V3VfBDnDeghCjkn9q7cF2TYMzFd3anxTX4xCHvhBMFpqI6d8rMPpO/NLQ39uzK8zx7/ADym5hL9MDLC/lamRap0AvAb9hzf7sEsTJU4AzlMOgHekzzCdBJ55UTJzbgH30vlXQV2hbb7TMUs5s9LcVC+bUyBIjuqU3fR2Lnos=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build
  - ./gradlew --scan -s
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube

###################################
### Upload Code Coverage Report ###
###################################
after_success:
  - bash <(curl -s https://codecov.io/bash)

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true
