######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk11

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "felixklauke"
    token:
      secure: XHCsT6nQXtD15fzwKUAaL5hoJlJe7T4RMtblV7Ntve3DsjG847gwcwK2jdXq7Nv0fMmsamIga/DWfF97zY0ceyoo5SPP2n5t+nr854zgtH92DCTqJtV9TcBpY2xswp1WDijxVLShVLrOvvzKogzRpwST7nZySnUvnfmWne5a76kvMEcmwKoLWHDs6Qol7Nbr202jvDgrjnfvCfQVv+NkIBKF8LW3r38kJdxzW2vlW7OgloZ+d5TiSEYERh6rvIuDaN0zMQCc/WzcF111+U0QmB+BozAtKjnQlJAtzDEcAPM5bXr2UlxS4Fiz7ZGOIvf+RCE22vRzJYB+gmszjl8MlFq+Fx4R+c4d3fsrdX98dAKuxgsyUkcjCJBd2Gaq+u7UkQowZz6ilkMP0LK+bksPCSG3xnELiuxwdvqqQhto1B/27+4GVZAi4lmm0VnNUMDKRgbBiO8nvCr4TiI9yaJQW8xDksZYCCAP9UKr7ls71UOylK4brOEVlubO3S4J9pECie+dPkX6EIyyBGkdcddfVG8NFCIFDVK/NuI955qaYv3QGzEHg7FxrIhHEAajCOU47bEBibIyW87w6CHEb5Ls/ma7NsO2H7ysF48SHkO18ljORphMQ85Rlv7ypydcHX4DBmH00FaqShMHzxBej1xHGkprGx7xSq9aiXwnH65XzzI=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build
  - ./gradlew --scan -s
  - ./gradlew codeCoverageReport
  - ./gradlew sonarqube

###################################
### Upload Code Coverage Report ###
###################################
after_success:
  - bash <(curl -s https://codecov.io/bash)

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    branch: master
    tags: true
